language: ruby
rvm:
  - 2.1.2

before_script:
  - wget https://gist.github.com/rafamanzo/6179925/raw/77653bd6229e99d5251180a4488e2fa54d0cd4ac/db_bootstrap.sql
  - wget https://gist.github.com/rafamanzo/6179925/raw/a38c3b33af3b1784eece46450cca65503337e4b5/install.sh
  - chmod +x install.sh
  - ./install.sh
  - cp features/support/kalibro_cucumber_helpers.yml.sample features/support/kalibro_cucumber_helpers.yml

script:
  - bundle exec rspec spec
  - bundle exec cucumber --tags ~@wip

notifications:
  email:
    recipients:
      - mezuro-core@lists.ime.usp.br
    on_success: change
    on_failure: always
