language: ruby
rvm:
  - 2.1.2

before_script:
  - git clone https://gist.github.com/0c4ad3b5700c6364abf1.git -b v1.0 kalibro_install
  - pushd kalibro_install
    # Remove bugged libzmq3 package, see https://github.com/travis-ci/travis-ci/issues/982 and https://github.com/travis-ci/travis-ci/issues/1715 for details
  - sudo apt-get remove libzmq3
  - bash install.sh
  - popd
  - cp features/support/kalibro_cucumber_helpers.yml.sample features/support/kalibro_cucumber_helpers.yml

script:
  - bundle exec rspec spec
  - bundle exec cucumber --tags ~@wip

notifications:
  email:
    recipients:
      - mezuro-core@lists.ime.usp.br
    on_success: change
    on_failure: always
